import React, { useEffect, useState } from 'react';
import { AlertOctagon, CheckCircle2, Loader2, Lock, X } from 'lucide-react';
import { fetchLearningSafety } from './api';
import { LearningSafety } from './types';

export default function SafetyPanel({open,onClose}:{open:boolean;onClose:()=>void}) {
  const [data,setData]=useState<LearningSafety|null>(null);const [error,setError]=useState('');
  useEffect(()=>{if(!open)return;setError('');void fetchLearningSafety().then(setData).catch(err=>setError(err instanceof Error?err.message:'加载失败'));},[open]);
  if(!open)return null;
  return <div className="fixed inset-0 z-[100] flex justify-end bg-black/65" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><aside className="flex h-full w-[470px] flex-col border-l border-[#303548] bg-[#10121a] shadow-2xl select-text"><div className="flex items-center justify-between border-b border-[#292e40] px-5 py-4"><div className="flex items-center gap-2"><Lock className="h-4 w-4 text-rose-400"/><div><h2 className="text-sm font-semibold">机筛安全门</h2><p className="text-[10px] text-slate-500">人工反馈只训练影子模型，不直接接管删除权</p></div></div><button onClick={onClose} className="rounded p-1 text-slate-500 hover:bg-[#232737] hover:text-white"><X className="h-4 w-4"/></button></div>{!data&&!error?<div className="flex flex-1 items-center justify-center gap-2 text-xs text-slate-400"><Loader2 className="h-4 w-4 animate-spin"/>正在回放这批人工决策…</div>:error?<div className="p-5 text-xs text-rose-400">{error}</div>:data&&<div className="overflow-auto p-5"><div className="rounded-lg border border-rose-800/70 bg-rose-950/30 p-4"><div className="flex items-start gap-3"><AlertOctagon className="mt-0.5 h-5 w-5 shrink-0 text-rose-400"/><div><div className="text-sm font-semibold text-rose-300">自动过滤仍被锁定</div><p className="mt-1 text-xs leading-5 text-slate-400">旧规则曾错拦 {data.approved_missed_by_old_filter}/{data.approved_unique} 首最终通过歌曲。宁可多给你一些误报，也不能把可能要的歌静默删掉。</p></div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Stat label="旧规则漏收率" value={`${(data.historical_miss_rate*100).toFixed(1)}%`} bad/><Stat label="影子模型召回率" value={`${(data.candidate_model.recall*100).toFixed(1)}%`}/><Stat label="影子模型精确率" value={`${(data.candidate_model.precision*100).toFixed(1)}%`} bad/><Stat label="有效人工样本" value={`${data.feedback_count}/${data.feedback_target}`}/></div><div className="mt-5"><div className="flex justify-between text-[11px] text-slate-400"><span>样本成熟度</span><span className="font-mono">{Math.min(100,Math.round(data.feedback_count/data.feedback_target*100))}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded bg-[#252938]"><div className="h-full bg-violet-500" style={{width:`${Math.min(100,data.feedback_count/data.feedback_target*100)}%`}}/></div></div><div className="mt-5 space-y-2"><Gate ok={data.gates.historical_miss_gate} label="历史漏收率 ≤ 0.5%"/><Gate ok={data.gates.candidate_quality_gate} label="召回率 ≥ 99%，且精确率 ≥ 25%"/><Gate ok={data.gates.sample_maturity_gate} label={`累计至少 ${data.feedback_target} 条人工标签`}/></div><div className="mt-5 rounded border border-[#2a2f42] bg-[#151822] p-3 text-[11px] leading-5 text-slate-400"><strong className="text-slate-200">接下来如何变聪明：</strong>系统已把你的“通过/否决”按歌曲、艺人、标题词、发行类型、平台和原机筛特征留档。每批审核后训练新版本，先在影子模式回放；只有三道安全门全过，才允许建议更强的预排序。即使解锁，也先不自动删除候选。</div></div>}</aside></div>;
}
function Stat({label,value,bad=false}:{label:string;value:string;bad?:boolean}){return <div className="rounded border border-[#292e40] bg-[#151822] p-3"><div className="text-[10px] text-slate-500">{label}</div><div className={`mt-1 font-mono text-xl ${bad?'text-rose-400':'text-slate-100'}`}>{value}</div></div>}
function Gate({ok,label}:{ok:boolean;label:string}){return <div className="flex items-center justify-between rounded border border-[#292e40] bg-[#151822] px-3 py-2.5 text-xs"><span className="text-slate-300">{label}</span>{ok?<span className="flex items-center gap-1 text-emerald-400"><CheckCircle2 className="h-3.5 w-3.5"/>通过</span>:<span className="flex items-center gap-1 text-rose-400"><Lock className="h-3.5 w-3.5"/>锁定</span>}</div>}
